{{- if (index .Values "ccx-monitoring").loki.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: loki-ingress-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  LOKI_USERNAME: {{ include "loki.username" . | default "ccx" | quote }}
  LOKI_PASSWORD: {{ include "loki.password" . | default (randAlphaNum 32) | quote }}
{{- end }}